# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/spaceship

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/spaceship

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/spaceship/CMakeFiles /storage/emulated/0/spaceship/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/spaceship/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spaceship

# Build rule for target.
spaceship: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spaceship
.PHONY : spaceship

# fast build rule for target.
spaceship/fast:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/build
.PHONY : spaceship/fast

src/drive.o: src/drive.cpp.o

.PHONY : src/drive.o

# target to build an object file
src/drive.cpp.o:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/drive.cpp.o
.PHONY : src/drive.cpp.o

src/drive.i: src/drive.cpp.i

.PHONY : src/drive.i

# target to preprocess a source file
src/drive.cpp.i:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/drive.cpp.i
.PHONY : src/drive.cpp.i

src/drive.s: src/drive.cpp.s

.PHONY : src/drive.s

# target to generate assembly for a file
src/drive.cpp.s:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/drive.cpp.s
.PHONY : src/drive.cpp.s

src/hull.o: src/hull.cpp.o

.PHONY : src/hull.o

# target to build an object file
src/hull.cpp.o:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/hull.cpp.o
.PHONY : src/hull.cpp.o

src/hull.i: src/hull.cpp.i

.PHONY : src/hull.i

# target to preprocess a source file
src/hull.cpp.i:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/hull.cpp.i
.PHONY : src/hull.cpp.i

src/hull.s: src/hull.cpp.s

.PHONY : src/hull.s

# target to generate assembly for a file
src/hull.cpp.s:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/hull.cpp.s
.PHONY : src/hull.cpp.s

src/journey.o: src/journey.cpp.o

.PHONY : src/journey.o

# target to build an object file
src/journey.cpp.o:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/journey.cpp.o
.PHONY : src/journey.cpp.o

src/journey.i: src/journey.cpp.i

.PHONY : src/journey.i

# target to preprocess a source file
src/journey.cpp.i:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/journey.cpp.i
.PHONY : src/journey.cpp.i

src/journey.s: src/journey.cpp.s

.PHONY : src/journey.s

# target to generate assembly for a file
src/journey.cpp.s:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/journey.cpp.s
.PHONY : src/journey.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/shield.o: src/shield.cpp.o

.PHONY : src/shield.o

# target to build an object file
src/shield.cpp.o:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/shield.cpp.o
.PHONY : src/shield.cpp.o

src/shield.i: src/shield.cpp.i

.PHONY : src/shield.i

# target to preprocess a source file
src/shield.cpp.i:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/shield.cpp.i
.PHONY : src/shield.cpp.i

src/shield.s: src/shield.cpp.s

.PHONY : src/shield.s

# target to generate assembly for a file
src/shield.cpp.s:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/shield.cpp.s
.PHONY : src/shield.cpp.s

src/spaceship.o: src/spaceship.cpp.o

.PHONY : src/spaceship.o

# target to build an object file
src/spaceship.cpp.o:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/spaceship.cpp.o
.PHONY : src/spaceship.cpp.o

src/spaceship.i: src/spaceship.cpp.i

.PHONY : src/spaceship.i

# target to preprocess a source file
src/spaceship.cpp.i:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/spaceship.cpp.i
.PHONY : src/spaceship.cpp.i

src/spaceship.s: src/spaceship.cpp.s

.PHONY : src/spaceship.s

# target to generate assembly for a file
src/spaceship.cpp.s:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/spaceship.cpp.s
.PHONY : src/spaceship.cpp.s

src/title.o: src/title.cpp.o

.PHONY : src/title.o

# target to build an object file
src/title.cpp.o:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/title.cpp.o
.PHONY : src/title.cpp.o

src/title.i: src/title.cpp.i

.PHONY : src/title.i

# target to preprocess a source file
src/title.cpp.i:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/title.cpp.i
.PHONY : src/title.cpp.i

src/title.s: src/title.cpp.s

.PHONY : src/title.s

# target to generate assembly for a file
src/title.cpp.s:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/title.cpp.s
.PHONY : src/title.cpp.s

src/weapon.o: src/weapon.cpp.o

.PHONY : src/weapon.o

# target to build an object file
src/weapon.cpp.o:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/weapon.cpp.o
.PHONY : src/weapon.cpp.o

src/weapon.i: src/weapon.cpp.i

.PHONY : src/weapon.i

# target to preprocess a source file
src/weapon.cpp.i:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/weapon.cpp.i
.PHONY : src/weapon.cpp.i

src/weapon.s: src/weapon.cpp.s

.PHONY : src/weapon.s

# target to generate assembly for a file
src/weapon.cpp.s:
	$(MAKE) -f CMakeFiles/spaceship.dir/build.make CMakeFiles/spaceship.dir/src/weapon.cpp.s
.PHONY : src/weapon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... spaceship"
	@echo "... src/drive.o"
	@echo "... src/drive.i"
	@echo "... src/drive.s"
	@echo "... src/hull.o"
	@echo "... src/hull.i"
	@echo "... src/hull.s"
	@echo "... src/journey.o"
	@echo "... src/journey.i"
	@echo "... src/journey.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shield.o"
	@echo "... src/shield.i"
	@echo "... src/shield.s"
	@echo "... src/spaceship.o"
	@echo "... src/spaceship.i"
	@echo "... src/spaceship.s"
	@echo "... src/title.o"
	@echo "... src/title.i"
	@echo "... src/title.s"
	@echo "... src/weapon.o"
	@echo "... src/weapon.i"
	@echo "... src/weapon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

